### ISSUE TITLE
How to install plugins and restart sonar properly?

### ISSUE THREAD

**Issue by dirceuSilva** [harbur/docker-sonarqube#2]
Hi guys, 

Congrats for the amazing job! 
However I am having some problems to install plugins into sonar instance started inside the docker container. Could you help me, please?

After request the plugin installation using the sonar Update Center GUI, I need to restart sonar. However, if I restart the containers using fig stop and fig up, the containers are recreated and I loose the pending installations. I've tried to use fig up --no-recreate but then a got an error and the sonar container does not start. I have seen nothing in the logs that explains to me which error causes the sonar container abortion. 

Could you please tell me, how did you project this couple of containers to expect plugins installations? Perhaps some data volume containers strategy can solve my problem. Is that an option?

Thanks in advance.

**Comment by spiddy** [comment]
Fixed at commit: 5e6559a

Now the container has VOLUMES declared, so there is no need for external volume management. It should work out-of-the-box now.

As an example, you should be able to do fig up, install plugins, fig stop, fig start (or fig up) and it should pick them up.

**Comment by dirceuSilva** [comment]
Thanks man,

It worked fine!

**Comment by spiddy** [comment]
:smiley:
