### ISSUE TITLE
fig.yml file not mentioned

### ISSUE THREAD

**Issue by frommeyerc** [harbur/docker-sonarqube#4]
Hi,

it just took me quite a while to find out that there is an important step missing between pulling the sonarqube image and running fig up. I.e. I have to get a matching fig.yml file. I found it in the github.com repo. It would be nice to put this info into the docu as well.

Anyways thanks a lot for creating and maintaining this image!

-Christian

**Comment by spiddy** [comment]
Added the reference to the fig.yml.

Thanks for the feedback
